[0m23:51:10.199631 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013858F26BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013859FD5850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013859FD5640>]}


============================== 23:51:10.215487 | ec5fd10e-0e85-4dd5-9ba3-46b16455109d ==============================
[0m23:51:10.215487 [info ] [MainThread]: Running with dbt=1.9.4
[0m23:51:10.218411 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\fitzp\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:51:10.218411 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fitzp\OneDrive\Desktop\Capstone_elt_Project\CAPSTONE_ELT_PROJECT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:51:10.220425 [debug] [MainThread]: Command `dbt run` failed at 23:51:10.220425 after 0.15 seconds
[0m23:51:10.222435 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013858F26BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013859FD55E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013859FD5640>]}
[0m23:51:10.223732 [debug] [MainThread]: Flushing usage events
[0m23:51:10.615682 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:53:58.122835 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000244B13B5B20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000244B24667C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000244B24665B0>]}


============================== 23:53:58.126382 | 01bb3448-9ff6-41dd-a92a-ca953f406470 ==============================
[0m23:53:58.126382 [info ] [MainThread]: Running with dbt=1.9.4
[0m23:53:58.128389 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\fitzp\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:53:58.130997 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fitzp\OneDrive\Desktop\Capstone_elt_Project\CAPSTONE_ELT_PROJECT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:53:58.130997 [debug] [MainThread]: Command `dbt run` failed at 23:53:58.130997 after 0.12 seconds
[0m23:53:58.132738 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000244B13B5B20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000244B2466550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000244B24665B0>]}
[0m23:53:58.132738 [debug] [MainThread]: Flushing usage events
[0m23:53:58.405612 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:55:30.937485 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D58145BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D5A1C07C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D5A1C09D0>]}


============================== 23:55:30.942550 | 30725ade-a2e5-4770-aad7-cd46671a5e3f ==============================
[0m23:55:30.942550 [info ] [MainThread]: Running with dbt=1.9.4
[0m23:55:30.944058 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\fitzp\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:55:30.946667 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fitzp\OneDrive\Desktop\Capstone_elt_Project\CAPSTONE_ELT_PROJECT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:55:30.946667 [debug] [MainThread]: Command `dbt run` failed at 23:55:30.946667 after 0.14 seconds
[0m23:55:30.949426 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D58145BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D5A1C0A30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D5A1C09D0>]}
[0m23:55:30.952235 [debug] [MainThread]: Flushing usage events
[0m23:55:31.323905 [debug] [MainThread]: An error was encountered while trying to flush usage events
